### ISSUE TITLE
10.3 Stack Management in a Function

### ISSUE THREAD

**Issue by justinhester** [justinhester/IntroCompOrg-RPi#10]
To match the description of `PUSH` on [10.1 Passing Arguments in Registers](http://bob.cs.sonoma.edu/IntroCompOrg-RPi/sec-reg-use.html) the paragraph describing the steps of `push {fp, lr}` in [10.3 Stack Management in a Function](http://bob.cs.sonoma.edu/IntroCompOrg-RPi/sec-stack-manage.html) should switch the order of steps 1 and 2 to read

    The push instruction at the beginning of this function:
      1. Pushes the return address, the value contained in the lr register, onto the stack.
      2. Pushes the caller's frame pointer, the value contained in the fp register, onto the stack.
      3. Updates the sp to show that two 32-bit values have been pushed onto the top of the stack.

To reach this reasoning, I opened Listing 10.1.4 `helloWorld1.s` in the debugger.

```
$ as --gstabs -o helloWorld1.o helloWorld1.s
$ gcc -o helloWorld1 helloWorld1.o
$ gdb ./helloWorld1
...
(gdb) br 27
Breakpoint 1 at 0x10440: file helloWorld1.s, line 27.
(gdb) r
Starting program: /home/pi/repos/IntroCompOrg-RPi/contents/chp10/helloWorld1

Breakpoint 1, main () at helloWorld1.s:28
28    add fp, sp, #4
(gdb) i r r11 fp lr
r11    0x0    0
fp    0x7efff598    0x7efff598
lr    0x76e8f678    1994978936
(gdb) x/3xw $sp
0x7efff598:    0x00000000    0x76e8f678    0x76fb4000
```

The stack appears to follow *full-descending* stack implementation where `lr` was pushed first followed by `r11` (previous `fp`). This satisfies the definition of `POP` in [10.1 Passing Arguments in Registers](http://bob.cs.sonoma.edu/IntroCompOrg-RPi/sec-reg-use.html) so that starting from the lowest numbered register `0x00000000` is popped into `r11` and `0x76e8f678` is popped into the higher numbered register `pc`.

```
(gdb) br 35
Breakpoint 2 at 0x1045c: file helloWorld1.s, line 35.
(gdb) c
Continuing.
Hello, World!

Breakpoint 2, main () at helloWorld1.s:35
35    pop    {fp, pc}
(gdb) i r r11 fp pc
r11    0x7efff59c    2130703772
fp    0x7efff59c    0x7efff59c
pc    0x1045c    0x1045c <main+32>
(gdb) si
...
325    lib-start.c: No such file or directory.
(gdb) i r r11 fp pc sp
r11    0x0    0
fp    0x7efff5a0    0x7efff5a0
pc    0x76e8f678    0x76e8f678 <__libc_start_main+276>
sp    0x7efff5a0    0x7efff5a0
```

**Comment by rplantz** [comment]
Fixed. I should have read the manual more carefully. :-(
