### ISSUE TITLE
13.2 Accessing Arguments in a Function

### ISSUE THREAD

**Issue by justinhester** [justinhester/IntroCompOrg-RPi#16]
The second sentence before Figure 13.2.10 (in order to match Figure 13.2.10) should read

> The frame pointer points to the calling function's **return address**, and the calling function's **frame pointer** is located −4 bytes offset from the frame pointer.

The code in `sumNine2.s` also reaffirms this correction as well

```
        sub     sp, sp, 8       @ space for fp, lr
        str     fp, [sp, 0]     @ save fp
        str     lr, [sp, 4]     @   and lr
        add     fp, sp, 4      @ set our frame pointer
```

If `fp` was pointing at the calling function's frame pointer, the fourth assembly language mnemonic would have to read

```
        add     fp, sp, 0      @ set our frame pointer
```

**Comment by rplantz** [comment]
Fixed.
