### ISSUE TITLE
16.6 Exercises

### ISSUE THREAD

**Issue by justinhester** [justinhester/IntroCompOrg-RPi#23]
## Problem 2 Corrections

- b. **bdcccccc<sub>16</sub>**
- f. **3ea8f5c2<sub>16</sub>**
- g. **bf2b8a3d<sub>16</sub>**
- h. **4048f5c2<sub>16</sub>**

See [exercises-32.md](https://github.com/justinhester/IntroCompOrg-RPi/blob/94e3f21b66a2cfcf4d1d6f0d4b17237b6b7582aa/contents/exercises/exercises-32/exercises-32.md) for steps.

**Comment by rplantz** [comment]
These answers are correct if you carry the computation out one more bit and then round off. I believe that most floating point hardware these days does the round off.

**Comment by justinhester** [comment]
Thank you! Yes, I didn't apply the rounding off to b, f and h as described in `16.1 Fractional Values in Binary`. I reviewed the computation for g though and updated the answer to `0xbf2e147b`. I did make a mistake with a missing zero in the infinite binary fraction `10101110000101000111`. But, the highest order hexadecimal digit of the solution should for example still be greater than or equal to 8, since the sign is negative.

**Comment by rplantz** [comment]
I believe my answer of 0xbf2b851f is correct for g. I double checked (after making a couple of errors doing it by hand) using a couple of online conversion programs. Frankly, if I were teaching from the book and a student made a simple error (like I have done several times), I would give credit for the answer. The point I am trying to make in the book is the general pattern of how floating-point numbers are stored. I am much less concerned with arithmetic accuracy.
