### ISSUE TITLE
Equation 5.3.2

### ISSUE THREAD

**Issue by justinhester** [justinhester/IntroCompOrg-RPi#6]
The second line

**= M<sub>2</sub> + M<sub>3</sub> + M<sub>4</sub> + M<sub>7</sub>**

is a sum of standard sum terms (maxterms) and should instead be a *product* of maxterms written as

**= M<sub>2</sub> ⋅ M<sub>3</sub> ⋅ M<sub>4</sub> ⋅ M<sub>7</sub>**

**Comment by rplantz** [comment]
Fixed.
