### ISSUE TITLE
Table 8.2.2

### ISSUE THREAD

**Issue by justinhester** [justinhester/IntroCompOrg-RPi#9]
The topmost column names do not match the previous sentence. They should be in the order

Low 32-bit | Full 64-bit | Register
:- | :- | :-

Otherwise, if the previous sentence was incorrect, then the column names would remain the same and that sentence should instead read

> `wn`, where n=0,1,…,30, refers to the entire 64 bits. Using `rn` or `xn`, where n=0,1,…,30, refers to the low-order 32-bit portion of the register.

**Comment by rplantz** [comment]
I corrected the table body to match the headings.
